name: Required Checks
description: Define required checks inside your repository.
author: "Rory Quinn"

inputs:
  required_workflow_patterns:
    description: List of regex patterns to check.
    required: true
  conditional_path_workflow_patterns:
    description: Dictionary of path globs and regex patterns to check. If a commit file matches a path glob then the corresponding patterns will be checked.
  token:
    description: GitHub token
  target_sha:
    description: Target SHA.
  initial_delay_seconds:
    description: Initial delay before polling.
  poll_frequency_seconds:
    description: Polling frequency.
  missing_required_retry_count:
    description: Number of times to retry if a required check is missing, for cases where the workflow is still being created.
  version:
    description: Release version of action to run.
runs:
  using: node20
  main: index.js
branding:
  icon: "shield"
  color: "blue"
