name: Required Checks
description: Define required checks inside your repository.
author: "Rory Quinn"

inputs:
  token:
    description: GitHub token
  required_workflow_patterns:
    description: List of patterns to check.
  target_sha:
    description: Target SHA.
  initial_delay_seconds:
    description: Initial delay before polling.
  poll_frequency_seconds:
    description: Polling frequency.
  missing_required_retry_count:
    description: Number of times to retry if a required check is missing, for cases where the workflow is still being created.
  version:
    description: Release version of action to run.
runs:
  using: node20
  main: index.js
branding:
  icon: "check-square"
  color: "green"
