name: Run Action

on:
  pull_request:

jobs:
  run-golang:
    env:
      REQUIRED_CHECKS_DEBUG: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - run: go run main.go
      env:
        INPUT_REQUIRED_WORKFLOW_PATTERNS: |
          - tests
        INPUT_CONDITIONAL_PATH_WORKFLOW_PATTERNS: |
          "**/*.go": [ "unit-tests" ]
        INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-master:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for required checks
        uses: roryq/required-checks@master
        with:
          # required-workflow-patterns is a yaml list of regex patterns to check
          required_workflow_patterns: |
            # will match any check with tests in its name
            - tests
            # will match either markdown-lint or yaml-lint
            - (markdown-lint|yaml-lint)
          # required lists based on conditional path globs
          conditional_path_workflow_patterns: |
            "**/*.go":
              - unit-tests
          # GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}
          # number of seconds to wait before starting the first poll
          initial_delay_seconds: 15
          # number of seconds to wait between polls
          poll_frequency_seconds: 30
          # number of times to retry if a required check is missing.
          # This is useful in cases where the workflow is still being created.
          missing_required_retry_count: 3
          # target sha that the checks have been run against. Defaults to ${{ github.event.pull_request.head.sha || github.sha }}
          target_sha: ${{ github.event.pull_request.head.sha || github.sha }}

